package net.sourceforge.vietpad;

import java.util.ListResourceBundle;

public class Resources extends ListResourceBundle
{
    static final Object [][] contents = {
        {"About_", "About "},
        {"Add_Diacritics", "Add Diacritics"},
        {"_and_try_again.", " and try again."},
        {"Cancel", "Cancel"},
        {"Cannot_find_\"", "Cannot find \""},
        {"Cannot_find_file_", "Cannot find file "},
        {"Change_Case", "Change Case"},
        {"Close", "Close"},
        {"Convert_to_Unicode", "Convert to Unicode"},
        {"Convert_to_VIQR", "Convert to VIQR"},
        {"Copy", "Copy"},
        {"Cut", "Cut"},
        {"Date_&_Time", "Date and Time"},
        {"Delete", "Delete"},
        {"Do_you_want_to_save_the_changes_to", "Do you want to save the changes to"},
        {"Edit", "Edit"},
        {"Error_reading_file_", "Error reading file "},
        {"Error_saving_file_", "Error saving file "},
        {"Exit", "Exit"},
        {"File", "File"},
        {"Find", "Find"},
        {"Font", "Font"},
        {"Format", "Format"},
        {"_has_run_out_of_memory.\nPlease_restart_", " has run out of memory.\nPlease restart "},
        {"Help", "Help"},
        {"Hide_Toolbar", "Hide Toolbar"},
        {"Input_Method", "Input Method"},
        {"Illegal_Argument", "Illegal Argument"},
        {"\"_in\n", "\" in\n"},                
        {"_is_not_a_file", " is not a file"},
        {"Keyboard", "Keyboard"},
        {"Keyboard_Mode", "Keyboard Mode"},
        {"Look_&_Feel", "Look and Feel"},
        {"\n\nTo_preserve_all_characters,_cancel_now", "\n\nTo preserve all characters, cancel now"},
        {"\nand_save_as_a_new_file_in_Unicode_UTF-8_or_UTF-16_format.", "\nand save as a new file in Unicode UTF-8 or UTF-16 format."},
        {"\nDo_you_still_want_to_proceed?", "\nDo you still want to proceed?"},
        {"New", "New"},
        {".\nFile_is_inaccessible.", ".\nFile is inaccessible."},
        {"Normalize_Diacritics", "Normalize Diacritics"},
        {"\nSaving_as_Windows_Latin_1_will_result_in_loss_of_those_characters.", "\nSaving as Western will result in loss of those characters."},
        {"OK", "OK"},
        {"Open", "Open"},
        {"Out_of_Memory", "Out of Memory"},
        {"Page_Setup", "Page Setup"},
        {"Pali", "Special Edition for Pali-Sanskrit & \u0110\u00EAga\n"},
        {"Paste", "Paste"},
        {"Please_enter_the_target_to_search", "Please enter the target to search"},
        {"Preferences", "Preferences"},
        {"Print", "Print"},
        {"readme", "readme.html"},
        {"Redo", "Redo"},
        {"Remove_Diacritics", "Remove Diacritics"},
        {"Remove_Line_Breaks", "Remove Line Breaks"},
        {"Replace", "Replace"},
        {"Save_As", "Save As"},
        {"Save_as_Windows_Latin_1", "Save as Western"},
        {"Save_Document", "Save Document"},
        {"Save", "Save"},
        {"Select_All", "Select All"},
        {"Shorthand", "Shorthand"},
        {"Show_Toolbar", "Show Toolbar"},
        {"SmartMark", "SmartMark"},
        {"Sort_Lines", "Sort Lines"},
        {"Spell_Check", "Spell Check"},       
        {"Strip_Diacritics", "Strip Diacritics"},
        {"The_file_appears_to_contain_Unicode_characters.", "The file appears to contain Unicode characters."},
        {"The_text_appears_to_be_already_in_Unicode_format.\nDo_you_still_want_to_proceed?", "The text appears to be already in Unicode format.\nDo you still want to proceed?"},
        {"The_text_appears_to_be_already_in_VIQR_format.\nDo_you_still_want_to_proceed?", "The text appears to be already in VIQR format.\nDo you still want to proceed?"},
        {"The_text_target_contains_an_illegal_character_'", "The text target contains an illegal character '"},
        {"Tools", "Tools"},
        {"Undo", "Undo"},
        {"Untitled", "Untitled"},
        {"Viet_Mode", "Viet Mode"},
        {"Vietnamese_Unicode_Text_Editor", "Vietnamese Unicode Text Editor\n"},
        {"View", "View"},
        {"Word_Wrap", "Word Wrap"},

    };

    @Override
    public Object [][] getContents() {
        return contents;
    }
}
