package net.sourceforge.vietpad;

import java.util.ListResourceBundle;

public class Resources_vi extends ListResourceBundle
{
    static final Object [][] contents = {
        {"About_", "Về "},
        {"Add_Diacritics", "Điền dấu"},
        {"_and_try_again.", " và thử lần nữa."},
        {"Cancel", "Bãi"},
        {"Cannot_find_file_", "Không thể tìm tập tin "},
        {"Cannot_find_\"", "Không tìm được \""},
        {"Change_Case", "Đổi ngữ cách"},
        {"Close", "Đóng"},
        {"Convert_to_Unicode", "Chuyển sang Unicode"},
        {"Convert_to_VIQR", "Chuyển sang VIQR"},
        {"Copy", "Sao"},
        {"Cut", "Cắt"},
        {"Date_&_Time", "Ngày và giờ"},
        {"Delete", "Xóa"},
        {"Do_you_want_to_save_the_changes_to", "Bạn có muốn lưu thay đổi vào"},
        {"Edit", "Soạn thảo"},
        {"Error_reading_file_", "Lỗi đọc tập tin "},
        {"Error_saving_file_", "Lỗi lưu tập tin "},
        {"Exit", "Thoát"},
        {"File", "Tập tin"},
        {"Find", "Tìm"},
        {"Font", "Phông"},
        {"Format", "Định dạng"},
        {"_has_run_out_of_memory.\nPlease_restart_", " đã hết bộ nhớ.\nHãy khởi động lại "},
        {"Help", "Trợ giúp"},
        {"Hide_Toolbar", "Giấu thanh công cụ"},
        {"Input_Method", "Kiểu gõ"},
        {"Illegal_Argument", "Thông số bất hợp lệ"},
        {"Keyboard", "Bàn phím"},
        {"Keyboard_Mode", "Mốt bàn phím"},
        {"\"_in\n", "\" trong\n"},                
        {"_is_not_a_file", " không phải là một tập tin"},
        {"Look_&_Feel", "Nhìn và cảm nhận"},
        {"\n\nTo_preserve_all_characters,_cancel_now", "\n\nĐể giữ tất cả ký tự, hãy bãi lệnh bây giờ"},
        {"\nand_save_as_a_new_file_in_Unicode_UTF-8_or_UTF-16_format.", "\nvà lưu như một tập tin mới với định dạng Unicode UTF-8 hay UTF-16."},
        {"\nDo_you_still_want_to_proceed?", "\nBạn vẫn muốn tiến hành?"},
        {"New", "Mới"},
        {".\nFile_is_inaccessible.", ".\nTập tin không truy cập được."},
        {"Normalize_Diacritics", "Bình thường hóa dấu"},
        {"\nSaving_as_Windows_Latin_1_will_result_in_loss_of_those_characters.", "\nLưu với định dạng Western sẽ làm mất những chữ đó."},
        {"OK", "Được"},
        {"Open", "Mở"},
        {"Out_of_Memory", "Hết bộ nhớ"},
        {"Page_Setup", "Sắp trang"},
        {"Pali", "Phiên bản đặc biệt cho Pali-Sanskrit & Đêga\n"},
        {"Paste", "Dán"},
        {"Please_enter_the_target_to_search", "Hãy nhập chữ mục tiêu kiếm"},
        {"Preferences", "Tùy thích"},
        {"Print", "In"},
        {"readme", "readme_vi.html"},
        {"Redo", "Làm lại"},
        {"Remove_Diacritics", "Khử dấu"},
        {"Remove_Line_Breaks", "Nối dòng"},
        {"Replace", "Thay"},
        {"Save_As", "Lưu vào"},
        {"Save_as_Windows_Latin_1", "Lưu với định dạng Western"},
        {"Save", "Lưu"},
        {"Select_All", "Chọn tất cả"},
        {"Shorthand", "Tốc ký"},
        {"Show_Toolbar", "Trưng thanh công cụ"},
        {"SmartMark", "Bỏ dấu thông minh"},
        {"Sort_Lines", "Xếp dòng"},
        {"Spell_Check", "Dò chính tả"},        
        {"Strip_Diacritics", "Tước dấu"},
        {"The_file_appears_to_contain_Unicode_characters.", "Văn bản có vẻ đã chứa các ký tự Unicode."},
        {"The_text_appears_to_be_already_in_Unicode_format.\nDo_you_still_want_to_proceed?", "Văn bản có vẻ đã trong định dạng Unicode.\nBạn vẫn muốn tiến hành?"},
        {"The_text_appears_to_be_already_in_VIQR_format.\nDo_you_still_want_to_proceed?", "Văn bản có vẻ đã trong định dạng VIQR.\nBạn vẫn muốn tiến hành?"},
        {"The_text_target_contains_an_illegal_character_'", "Chữ mục tiêu chứa một chữ không hợp lệ '"},
        {"Tools", "Công cụ"},
        {"Undo", "Hồi lại"},
        {"Untitled", "Không tên"},
        {"Viet_Mode", "Mốt tiếng Việt"},
        {"Vietnamese_Unicode_Text_Editor", "Trình duyệt văn bản Việt Unicode\n"},
        {"View", "Cảnh trí"},
        {"Word_Wrap", "Xuống hàng"},

    };
    
    @Override
    public Object [][] getContents() {
        return contents;
    }
}
